### ISSUE TITLE
Example for configuring format of Logger

### ISSUE THREAD

**Issue by tobstarr** [wojtekmach/mix_install_examples#1]
I would really like to see an example for how to configure the Logger in an elixir script.

What I tried so far is to call 

```elixir
Application.put_env(:logger, :console, format: "[$level] $message\n")

require Logger
Logger.info("hello")
Logger.info("world")
```

before I do `require Logger` but it seems to not do the trick:
```elixir

10:36:50.115 [info]  hello

10:36:50.116 [info]  world
```

All examples I found so far only cover configuring the logger for mix projects.

Or could it be that the logger process is actually started before the script is executed so that changing the env is too late?

**Comment by wojtekmach** [comment]
> Or could it be that the logger process is actually started before the script is executed so that changing the env is too late?

Yup, precisely.

the `bin/elixir` script calls the private `:elixir.start_cli/0` (https://github.com/elixir-lang/elixir/blob/v1.12.2/bin/elixir#L207) which in turn starts the logger (https://github.com/elixir-lang/elixir/blob/v1.12.2/lib/elixir/src/elixir.erl#L151:L159)

Not sure how reliable this is, but here's a workaround:

```elixir
# foo.exs
Application.stop(:logger)
Application.put_env(:logger, :console, format: "[$level] $message\n")
{:ok, _} = Application.ensure_all_started(:logger)

require Logger
Logger.info("hi")
```

```
$ elixir foo.exs
[info] hi
```

**Comment by wojtekmach** [comment]
We plan to extend Mix.install to support configuration, something like this:

```elixir
Mix.install(
  [
    :mime
  ],
  config: [
    mime: [
      types: %{
        "application/vnd.api+json" => ["json-api"]
      }
    ]
  ]
)
```

and the idea is that the configuration for a given dep is part of the cache key, so if the configuration changes, we recompile that dep.

perhaps we'd support configuring logger through Mix.install then but unsure. I'm gonna close this since it is not actionable for this repo but feel free to continue the discussion. :)

**Comment by tobstarr** [comment]
Nice one and thanks for the quick response!
