### ISSUE TITLE
Idea: demonstrating the use of Config from a one-off script

### ISSUE THREAD

**Issue by thbar** [wojtekmach/mix_install_examples#10]
Today I wanted to see if it is possible to add some `Config` to a `Mix.install` script, and apparently it works nicely, at least to some extent.

I wonder if you think it would be a good idea to add a sample to this repo.

E.g.

```elixir
# config.exs

import Config

config :hello, some_data: "world"
```

Then:

```elixir
#!/usr/bin/env elixir

data = Config.Reader.read!("config.exs")
Mix.install([...])

IO.inspect(data)
```

Gives:

```elixir
[hello: [some_data: "world"]]
```

I am not completely aware of the limitations of this approach, but I so far find it useful when designing something as a "bunch of exs scripts" initially, then add some config, and maybe (or maybe not) promoting this to a mix project later, if needed.

**Comment by wojtekmach** [comment]
Thank you for your suggestion. I’d really prefer to keep scripts as self-contained as possible so I would rather not show examples where we depend on external files. Since I think 1.13, we can pass :config option to Mix.install to configure apps which should cover some of the configuration needs.

**Comment by thbar** [comment]
@wojtekmach sounds good! Thanks for evaluating.
