### ISSUE TITLE
Phoenix + LiveView minimalistic example?

### ISSUE THREAD

**Issue by thbar** [wojtekmach/mix_install_examples#2]
I think the work you are doing is very essential ; being able to have short script run slightly complex stuff (e.g. starting a little server with a small database, migrate what's needed etc) is of tremendous use for prototyping and ideas dissemination. So thanks!

I have always wanted to have a single-file Phoenix example for simple stuff, and in particular LiveView. This is something I have started to pursue but not finish at this point.

With the introduction of `esbuild` in Phoenix 1.6, I feel we are getting closer from that.

Just opening this issue to know if you have already started working on something, or would be interested in such an example, as I feel it could be quite amazing.

In my case I would use it to quickly demonstrate real-time transportation data (SIRI/GTFS-RT formats) integration with LiveView, or other similar things.

Let me know what you think!

**Comment by wojtekmach** [comment]
A `phoenix_live_view.exs` addition to this repo would be really cool. I feel like it might be pushing things a bit too hard but on the other hand, if we can do _that_ then we can pretty much do anything. :) Please send a PR!

@teamon published a while ago some stuff related to this [1] [2] so it could be a good starting point.

[1] https://twitter.com/iteamon/status/1410175092546490368
[2] https://gist.github.com/teamon/a964dd80bc5c6802e3a8548efdda9cff

**Comment by josevalim** [comment]
We do have a single file phoenix live dashboard, which uses live view, and I believe may be a helpful setup too: https://github.com/phoenixframework/phoenix_live_dashboard/blob/master/dev.exs

**Comment by thbar** [comment]
FYI, I have started preliminary work at https://github.com/thbar/minimalistic-phoenix-liveview-esbuild, for now not as a `Mix.install/2` script, but just starting from a `--live` enabled Phoenix 1.6 RC setup. I will continue until I'm happy, and will prepare a PR once I'm there.

**Comment by thbar** [comment]
@wojtekmach first PR is read in #3. A bit of changes in `Mix.install/2` will be required to reduce the code (I had to copy-paste some Mix code to figure out where the javascript dependencies are etc), I believe.

**Comment by wojtekmach** [comment]
Closing in favour of a PR!
