### ISSUE TITLE
question : how to inject a config to a dependency that requires one

### ISSUE THREAD

**Issue by setop** [wojtekmach/mix_install_examples#33]
Hi,

I 'd like to use mix install in a self contained script that sends an email.

For that, I use Bamboo. But it require some configuration, like the adapter. Then the adapter needs a configuration too.
How can I achieve that ?

Thanks for the support.

**Comment by wojtekmach** [comment]
Mix.install accepts a :config option where you can configure apps. You can call Application.put_env before Mix.install too. Hope that helps.
