### ISSUE TITLE
Folders or additional files for "related/sub" projects?

### ISSUE THREAD

**Issue by zachdaniel** [wojtekmach/mix_install_examples#40]
I recently put together a small example based on the `plug` and `ash` examples here that showcase using `AshJsonApi`. I realized I could potentially PR that new example here, but I don't want to have a whole bunch of `ash_` packages in the main list (well, I'd be fine with it, but I don't want it to look like I'm trying to astroturf the lib over time if I have examples of each package 😆 ).

https://gist.githubusercontent.com/zachdaniel/0b8cb27391ca37b71bf9933f465350d5/raw/ec760ee32ff0cb76945ceb5b2dec3326eba37880/ash_json_api_example.exs

If you're interested in this (all good if not), should I create an `ash` folder and put the ash related stuff in there? Or just create an `ash_json_api` file alongside the `ash` file?

**Comment by wojtekmach** [comment]
If it's a few ash* files either way is fine, totally up to you though I'd slightly prefer to keep things flat. If you anticipate having more files, arbitrarily say 5+, I'd consider an ash_examples repo. I'm happy to link out to it! WDYT?

**Comment by zachdaniel** [comment]
For now in that case we'll just add some new ones like `ash_json_api.exs`, and if there are enough that its a problem we'll figure it out then.
