### ISSUE TITLE
libcurl example via Zig

### ISSUE THREAD

**Issue by ndrean** [wojtekmach/mix_install_examples#48]
I can't run it nor can fix it
<https://curl.se/libcurl/c/curl_easy_init.html>

```
error: no field named 'Struct' in union 'builtin.Type'
```

**Comment by wojtekmach** [comment]
Are you using Zig downloaded by Zigler or your own? If so, what version? Could you show your entire usage, OS version, anything else that can be relevant.

**Comment by ndrean** [comment]
ah, indeed. 
Using my Zig: 0.14.0-dev.2414+ba37a4369 (master)

Switched to 0.13.0 and it works.

My usage is just ctrl-c your snippet into an iex session.

I spoke too quickly. The [zigler add_f64](https://github.com/wojtekmach/mix_install_examples/blob/main/zigler.exs) does not work neither with my version, but works with 0.13.0

🤔

I opened an Elixir app with embedded Zig via Zigler. When I compile, I get 0.13.0.

```
[info] zig expected (via cache) in .../Library/Caches/zigler/zig-macos-aarch64-0.13.0/zig
```

So I should close this one in order to not confuse anyone.
