### ISSUE TITLE
ecto_sql example not working

### ISSUE THREAD

**Issue by fchabouis** [wojtekmach/mix_install_examples#5]
Hello,
I am enjoying a lot your code examples, that's an excellent idea. So I would like to first thank you about that.
I just tried to launch the ecto_sql example, and I get an exception :

```
(MatchError) no match of right hand side value: {:error, "killed"}
    ecto_sql.exs:41: Main.main/0
    (elixir 1.12.2) lib/code.ex:1261: Code.require_file/2
```

Are there any prerequisites, like things I should have installed on my computer before launching the example ? I do have Postgres installed already.

Thanks !

**Comment by wojtekmach** [comment]
Hey, thanks for the kind words!

the example should work out of the box as long as you have pg server running. It looks like there's a problem connecting to your server, perhaps an authentication issue? If no error is logged, maybe try this:

```diff
-:ok = Repo.__adapter__().storage_up(Repo.config())
+_ = Repo.__adapter__().storage_up(Repo.config())
+Process.sleep(500)
```

**Comment by fchabouis** [comment]
Ok thanks, I managed to launch it !

What the script was doing (or not) was not very clear to me. So you need to first create a database, for example using `createdb mix_install_examples`. Then I replaced the following statement : 

```diff
-Application.put_env(:foo, Repo, database: "mix_install_examples")
+Application.put_env(:foo, Repo, url: "ecto://postgres:postgres@localhost/mix_install_examples")
```
as I can access locally the database with the user `postgres` and the password `postgres`.

Maybe a little comment on top of the script could be useful ?

**Comment by wojtekmach** [comment]
> So you need to first create a database, for example using createdb mix_install_examples

that is handled by `Repo.__adapter__().storage_up(Repo.config())`.

When you run the script earlier, did you see any logger output? It should have contained the relevant information, e.g. server not being there, wrong auth, etc.

**Comment by wojtekmach** [comment]
I'm gonna close this as I believe the example works out of the box, that is, it requires a running pg instance that the current user can connect to, same as `$ psql` would. Feel free to continue the conversation though!

**Comment by johnnycyberseed** [comment]
_(... years later ...)_

When I'm running the database in a container (e.g. docker or colima) — rather than Postgres installed locally — I've only been able to connect to the database using the `url:` key _in_ the `Application.put_env(...)` call...

```
...
username = System.get_env("DB_USERNAME") || "postgres"
password = System.get_env("DB_PASSWORD")
Application.put_env(:foo, Repo, url: "ecto://#{username}:#{password}@localhost/mix_install_examples")

defmodule Repo do
  use Ecto.Repo,
    adapter: Ecto.Adapters.Postgres,
    otp_app: :foo
end
...
```

Any thoughts on why that would behave differently than specifying those same details in a config block (as committed to the repo)?

 🤔

**Comment by wojtekmach** [comment]
Sorry, could you paste a snippet that works and another one that does not?
